check_links.yaml total copy of docs.uppamx

diff --git a/.github/workflows/check_links.yaml b/.github/workflows/check_links.yaml
--- a/.github/workflows/check_links.yaml
+++ b/.github/workflows/check_links.yaml
@@ -25,6 +25,16 @@ jobs:
           INPUT_SCHEMA: .github/workflows/valid_json_schema.json
           INPUT_JSONS: mlc_config.json
 
+      # These are status code that cannot be ignored.
+      #
+      # If there is a valid external link that fails,
+      # add it to mlc_config.json
+      - name: External links must be checked, do not allow '0' in the 'aliveStatusCodes' of mlc_config.json
+        run: if [[ $(grep --regexp "[^0-9]0[^0-9]" mlc_config.json | wc --lines) == "1" ]]; then echo "FOUND"; exit 42; fi
+
+      - name: Internal links must checked, do not allow '400' in the 'aliveStatusCodes' of mlc_config.json
+        run: if [[ $(grep --regexp "[^0-9]400[^0-9]" mlc_config.json | wc --lines) == "1" ]]; then echo "FOUND"; exit 42; fi
+
       - uses: gaurav-nelson/github-action-markdown-link-check@v1
         with:
           config-file: 'mlc_config.json'
